name: Deploy to CPanel

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debug Step: List files before uploading
      - name: List all files in aleph directory
        run: ls -R ./aleph || echo "Directory not found"

      # Ensure the files are properly tarred before uploading
      - name: Create a compressed archive
        run: tar -czf aleph.tar.gz -C aleph .

      # Upload files via SCP
      - name: Deploy files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_HOST }}  # Your CPanel FTP host
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          source: aleph.tar.gz
          target: /public_html/miradi/  # Upload to this directory
          overwrite: true
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false

      # Extract the tar file on the server
      - name: Extract files on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          script: |
            cd /public_html/miradi/
            tar -xzf aleph.tar.gz
            rm aleph.tar.gz  # Clean up after extraction
